## **PYTORCH BACK PROPAGATION**

In [1]:
import torch

In [2]:
x = torch.tensor(4.0, requires_grad = True)

In [3]:
x

tensor(4., requires_grad=True)

In [4]:
y = x**2

In [5]:
y

tensor(16., grad_fn=<PowBackward0>)

In [6]:
## BackPropagation y = 2*x

y.backward()

In [7]:
print(x.grad)

tensor(8.)


In [10]:
lst = [[1.,2.,3.],[1.,2.,3.],[1.,2.,3.]]
torch_input = torch.tensor(lst, requires_grad=True)
torch_input

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]], requires_grad=True)

In [11]:
# y = x**3 + x**2

y = torch_input**3 + torch_input**2

In [12]:
y

tensor([[ 2., 12., 36.],
        [ 2., 12., 36.],
        [ 2., 12., 36.]], grad_fn=<AddBackward0>)

In [15]:
z = y.sum()

In [16]:
z.backward()

In [17]:
torch_input.grad

tensor([[ 5., 16., 33.],
        [ 5., 16., 33.],
        [ 5., 16., 33.]])