## **PyTorch ANN Project - House Price Prediction**
---
---

**Import Libraries**

In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

**Load Data Set**

In [7]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive


In [8]:
df = pd.read_csv("/content/drive/MyDrive/INeuron | Tensorflow/Data/houseprice.csv")

In [9]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

**Pick Important features - Create DataFrame**

In [10]:


df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [11]:
df = df[['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street','LotShape', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'SalePrice']]

In [12]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   
3          70       RL         60.0     9550   Pave      IR1       1915   
4          60       RL         84.0    14260   Pave      IR1       2000   

   1stFlrSF  2ndFlrSF  SalePrice  
0       856       854     208500  
1      1262         0     181500  
2       920       866     223500  
3       961       756     140000  
4      1145      1053     250000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1460 non-null   int64  
 1   MSZoning     1460 non-null   object 
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1460 non-null   int64  
 4   Street       1460 non-null   object 
 5   LotShape     1460 non-null   object 
 6   YearBuilt    1460 non-null   int64  
 7   1stFlrSF     1460 non-null   int64  
 8   2ndFlrSF     1460 non-null   int64  
 9   SalePrice    1460 non-null   int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 114.2+ KB


In [14]:
df.describe()

MSSubClass  LotFrontage        LotArea    YearBuilt     1stFlrSF  \
count  1460.000000  1201.000000    1460.000000  1460.000000  1460.000000   
mean     56.897260    70.049958   10516.828082  1971.267808  1162.626712   
std      42.300571    24.284752    9981.264932    30.202904   386.587738   
min      20.000000    21.000000    1300.000000  1872.000000   334.000000   
25%      20.000000    59.000000    7553.500000  1954.000000   882.000000   
50%      50.000000    69.000000    9478.500000  1973.000000  1087.000000   
75%      70.000000    80.000000   11601.500000  2000.000000  1391.250000   
max     190.000000   313.000000  215245.000000  2010.000000  4692.000000   

          2ndFlrSF      SalePrice  
count  1460.000000    1460.000000  
mean    346.992466  180921.195890  
std     436.528436   79442.502883  
min       0.000000   34900.000000  
25%       0.000000  129975.000000  
50%       0.000000  163000.000000  
75%     728.000000  214000.000000  
max    2065.000000  755000.000000

## **Check Unique Values**

In [15]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'SalePrice'],
      dtype='object')

In [16]:
df['MSSubClass'].unique()

array([ 60,  20,  70,  50, 190,  45,  90, 120,  30,  85,  80, 160,  75,
       180,  40])

In [17]:
len(df['MSSubClass'].unique())

15

In [18]:
for i in df.columns:
  print(" Column {} contain unique values : {}".format(i, len(df[i].unique())))

 Column MSSubClass contain unique values : 15
 Column MSZoning contain unique values : 5
 Column LotFrontage contain unique values : 111
 Column LotArea contain unique values : 1073
 Column Street contain unique values : 2
 Column LotShape contain unique values : 4
 Column YearBuilt contain unique values : 112
 Column 1stFlrSF contain unique values : 753
 Column 2ndFlrSF contain unique values : 417
 Column SalePrice contain unique values : 663


**Conclusion :**

*Categorical Column : 4*

*Continious COlumn  : 6*

## **Calculate the Age of House**

In [19]:
import datetime

datetime.datetime.now().year

2023

In [20]:
df['Total_years'] = datetime.datetime.now().year - df['YearBuilt']

In [21]:
df['Total_years']

0        20
1        47
2        22
3       108
4        23
       ... 
1455     24
1456     45
1457     82
1458     73
1459     58
Name: Total_years, Length: 1460, dtype: int64

In [22]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   
3          70       RL         60.0     9550   Pave      IR1       1915   
4          60       RL         84.0    14260   Pave      IR1       2000   

   1stFlrSF  2ndFlrSF  SalePrice  Total_years  
0       856       854     208500           20  
1      1262         0     181500           47  
2       920       866     223500           22  
3       961       756     140000          108  
4      1145      1053     250000           23

**Conclusion :**

'Total_years' column added

next approach is to delete 'YearBuilt'

In [23]:
df = df.drop('YearBuilt', axis = 1)

In [24]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  1stFlrSF  \
0          60       RL         65.0     8450   Pave      Reg       856   
1          20       RL         80.0     9600   Pave      Reg      1262   
2          60       RL         68.0    11250   Pave      IR1       920   
3          70       RL         60.0     9550   Pave      IR1       961   
4          60       RL         84.0    14260   Pave      IR1      1145   

   2ndFlrSF  SalePrice  Total_years  
0       854     208500           20  
1         0     181500           47  
2       866     223500           22  
3       756     140000          108  
4      1053     250000           23

## **Split Feature : Categorical Feature and Continious Feature**

In [25]:
categorical_feature = ['MSSubClass', 'MSZoning', 'Street', 'LotShape' ]

continious_feature  = ['LotFrontage', 'LotArea', '1stFlrSF', '2ndFlrSF', 'SalePrice', 'Total_years']

---
---
## **Label Encoding - Categorical Feature**

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
# Sample Example

encoder = LabelEncoder()
df['MSSubClass'] = encoder.fit_transform(df['MSSubClass'])
df['MSSubClass']

0       5
1       0
2       5
3       6
4       5
       ..
1455    5
1456    0
1457    6
1458    0
1459    0
Name: MSSubClass, Length: 1460, dtype: int64

In [28]:
# Mass Change

for i in categorical_feature:
  df[i] = encoder.fit_transform(df[i])

In [29]:
df[categorical_feature]

MSSubClass  MSZoning  Street  LotShape
0              5         3       1         3
1              0         3       1         3
2              5         3       1         0
3              6         3       1         0
4              5         3       1         0
...          ...       ...     ...       ...
1455           5         3       1         3
1456           0         3       1         3
1457           6         3       1         3
1458           0         3       1         3
1459           0         3       1         3

[1460 rows x 4 columns]

---
---
## **Categorical Feature -> Tensor Int Values**

In [30]:
import torch

In [31]:
cat_values = np.stack([df[i].values for i in categorical_feature], axis = 1)
cat_values = torch.tensor(cat_values, dtype = torch.int64)
cat_values

# Categorical Feature should be in INT value.

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

---
---
## **Continious Feature -> Tensor Float Values**

In [32]:
continious_feature

['LotFrontage', 'LotArea', '1stFlrSF', '2ndFlrSF', 'SalePrice', 'Total_years']

In [33]:
con_values = np.stack([df[i].values for i in continious_feature], axis = 1)
con_values = torch.tensor(con_values, dtype = torch.float32)
con_values

tensor([[6.5000e+01, 8.4500e+03, 8.5600e+02, 8.5400e+02, 2.0850e+05, 2.0000e+01],
        [8.0000e+01, 9.6000e+03, 1.2620e+03, 0.0000e+00, 1.8150e+05, 4.7000e+01],
        [6.8000e+01, 1.1250e+04, 9.2000e+02, 8.6600e+02, 2.2350e+05, 2.2000e+01],
        ...,
        [6.6000e+01, 9.0420e+03, 1.1880e+03, 1.1520e+03, 2.6650e+05, 8.2000e+01],
        [6.8000e+01, 9.7170e+03, 1.0780e+03, 0.0000e+00, 1.4212e+05, 7.3000e+01],
        [7.5000e+01, 9.9370e+03, 1.2560e+03, 0.0000e+00, 1.4750e+05, 5.8000e+01]])

In [34]:
con_values.dtype

torch.float32

---
---
## **Dependedent Feature**

In [35]:
y = torch.tensor(df['SalePrice'].values, dtype = torch.float).reshape(-1,1)

# reshape is necessary to create a 2 dimensional feature
y

tensor([[208500.],
        [181500.],
        [223500.],
        ...,
        [266500.],
        [142125.],
        [147500.]])

---
---
## **Find out Embedding Size(Dimension) for Categorical Feature**

*Embedding can be done only for Categorical Feature*

**Thumb Rule:**

Output Dimension should be set based on Input Dimension =>

Min(50, Feature Dimension/2)

In [36]:
# Categorical Features

categorical_feature

['MSSubClass', 'MSZoning', 'Street', 'LotShape']

In [37]:
# Find out the Dimension of 1 Categorical Features

len(df['MSSubClass'].unique())

15

In [38]:
# Find out the Dimension of all Categorical Features - at a time

categorical_dimension = [len(df[i].unique()) for i in df[categorical_feature]]
categorical_dimension

[15, 5, 2, 4]

In [39]:
# Find out the Embedding Dimension

embedding_dim = [(x, int(min(50, (x+1)/2))) for x in categorical_dimension]
embedding_dim

[(15, 8), (5, 3), (2, 1), (4, 2)]

### **Conclusion :**

'MSSubClass' input Feature : 15 & Output Feature : 8

'MSZoning'   input Feature : 5 & Output Feature : 3

'Street'     input Feature : 2 & Output Feature : 1,

'LotShape'   input Feature : 4 & Output Feature : 2

---
---
## **Represent Embedded Layers by using Module List - PyTorch**

In [40]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [41]:
embedded_representation = nn.ModuleList([nn.Embedding(inp, out) for inp,out in embedding_dim])
embedded_representation

ModuleList(
  (0): Embedding(15, 8)
  (1): Embedding(5, 3)
  (2): Embedding(2, 1)
  (3): Embedding(4, 2)
)

In [42]:
# Sample Example

cat_values[:4]
cat_values

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [43]:
# Moto : for Module 0, convert the 15 input unique Features to 8 output Features by using Embedding technique

pd.set_option('display.max_rows', 500)
embedding_val = []

for i, e in enumerate(embedded_representation):
  embedding_val.append(e(cat_values[:, i]))

In [44]:
embedding_val

[tensor([[ 1.5949, -0.8082, -0.4737,  ..., -0.7049, -0.5175,  0.7193],
         [-1.0798,  0.1101,  0.6303,  ..., -0.4943, -1.2520, -0.0154],
         [ 1.5949, -0.8082, -0.4737,  ..., -0.7049, -0.5175,  0.7193],
         ...,
         [ 0.1001,  1.1190, -0.4635,  ..., -0.1412, -1.2880, -0.1006],
         [-1.0798,  0.1101,  0.6303,  ..., -0.4943, -1.2520, -0.0154],
         [-1.0798,  0.1101,  0.6303,  ..., -0.4943, -1.2520, -0.0154]],
        grad_fn=<EmbeddingBackward0>),
 tensor([[0.8036, 2.0153, 0.8061],
         [0.8036, 2.0153, 0.8061],
         [0.8036, 2.0153, 0.8061],
         ...,
         [0.8036, 2.0153, 0.8061],
         [0.8036, 2.0153, 0.8061],
         [0.8036, 2.0153, 0.8061]], grad_fn=<EmbeddingBackward0>),
 tensor([[0.1271],
         [0.1271],
         [0.1271],
         ...,
         [0.1271],
         [0.1271],
         [0.1271]], grad_fn=<EmbeddingBackward0>),
 tensor([[-0.5506,  1.2333],
         [-0.5506,  1.2333],
         [-0.2570, -0.1147],
         ...,
   

### **Rearranging the Rows**

In [45]:
z = torch.cat(embedding_val, axis = 1)
z

tensor([[ 1.5949, -0.8082, -0.4737,  ...,  0.1271, -0.5506,  1.2333],
        [-1.0798,  0.1101,  0.6303,  ...,  0.1271, -0.5506,  1.2333],
        [ 1.5949, -0.8082, -0.4737,  ...,  0.1271, -0.2570, -0.1147],
        ...,
        [ 0.1001,  1.1190, -0.4635,  ...,  0.1271, -0.5506,  1.2333],
        [-1.0798,  0.1101,  0.6303,  ...,  0.1271, -0.5506,  1.2333],
        [-1.0798,  0.1101,  0.6303,  ...,  0.1271, -0.5506,  1.2333]],
       grad_fn=<CatBackward0>)

---
---
### **Implement Dropout**

In [46]:
dropout = nn.Dropout(.4)

In [47]:
final_embedded = dropout(z)
final_embedded

tensor([[ 2.6582, -1.3470, -0.0000,  ...,  0.2118, -0.0000,  0.0000],
        [-1.7996,  0.1835,  1.0505,  ...,  0.2118, -0.9177,  2.0556],
        [ 2.6582, -1.3470, -0.7896,  ...,  0.2118, -0.4284, -0.1912],
        ...,
        [ 0.1669,  1.8650, -0.0000,  ...,  0.2118, -0.0000,  0.0000],
        [-1.7996,  0.1835,  1.0505,  ...,  0.2118, -0.9177,  2.0556],
        [-0.0000,  0.1835,  0.0000,  ...,  0.0000, -0.0000,  2.0556]],
       grad_fn=<MulBackward0>)

In [48]:
class TabularModel(nn.Module):

    def __init__(self, emb_szs, n_cont, out_sz, layers, p=0.5):
        super().__init__()
        self.embeds = nn.ModuleList([nn.Embedding(ni, nf) for ni,nf in emb_szs])
        self.emb_drop = nn.Dropout(p)
        self.bn_cont = nn.BatchNorm1d(n_cont)

        layerlist = []
        n_emb = sum((nf for ni,nf in emb_szs))
        n_in = n_emb + n_cont

        for i in layers:
            layerlist.append(nn.Linear(n_in,i))
            layerlist.append(nn.ReLU(inplace=True))
            layerlist.append(nn.BatchNorm1d(i))
            layerlist.append(nn.Dropout(p))
            n_in = i
        layerlist.append(nn.Linear(layers[-1],out_sz))

        self.layers = nn.Sequential(*layerlist)

    def forward(self, x_cat, x_cont):
        embeddings = []
        for i,e in enumerate(self.embeds):
            embeddings.append(e(x_cat[:,i]))
        x = torch.cat(embeddings, 1)
        x = self.emb_drop(x)

        x_cont = self.bn_cont(x_cont)
        x = torch.cat([x, x_cont], 1)
        x = self.layers(x)
        return x