# **TENSORFLOW**
---
---

**VERSION CHECK**

In [1]:
import tensorflow as tf

print("TensorFlow Version : {}".format(tf.__version__))
print("Keras Version : {}".format(tf.keras.__version__))
print("Eager execution is {}".format(tf.executing_eagerly()))

TensorFlow Version : 2.12.0
Keras Version : 2.12.0
Eager execution is True


---
---
## **TENSOR CONSTANT**

In [2]:
# Define Constant

ineuron = tf.constant(42)
ineuron

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [3]:
# Define Constant with Specific Data Type

ineuron = tf.constant(42, dtype = tf.int64)
ineuron

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [4]:
ineuron.numpy()

42

In [5]:
# Define Constant Matrix

ineuron_x = tf.constant(([4,2],[9,5]))
ineuron_x


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]], dtype=int32)>

In [6]:
ineuron_x.numpy()

array([[4, 2],
       [9, 5]], dtype=int32)

In [7]:
# Check Shape and Data type

print(ineuron_x.shape)
print(ineuron_x.dtype)

(2, 2)
<dtype: 'int32'>


---
---
## **Generate matrix with only 1s and 0s**

In [8]:
tf.ones(shape = (3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [9]:
print(tf.ones(shape = (3,2)))

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [10]:
tf.zeros(shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

---
---
# **Matrix Summation**

In [11]:
const1 = tf.constant(([5,3,2],[1,2,3]))
const2 = tf.constant(([1,1,1],[2,2,2]))

result = tf.add(const1, const2)

print(result)

tf.Tensor(
[[6 4 3]
 [3 4 5]], shape=(2, 3), dtype=int32)


**Random Constant from Normal Distribution**

In [12]:
tf.random.normal(shape = (2,3), mean = 0, stddev = 1.0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.3707638 , -0.36289307, -1.4372827 ],
       [ 0.5586187 , -2.9629285 ,  0.25636846]], dtype=float32)>

**Random Constant from Uniform Distribution**

In [13]:
tf.random.uniform(shape = (3,2), minval = 0, maxval = 1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.08820987, 0.9770602 ],
       [0.9101958 , 0.15958357],
       [0.41762066, 0.0749408 ]], dtype=float32)>

---
---

## **VARIABLES**

In [14]:
var0 = 24 # python Variable

var1 = tf.Variable(24) # rank 0 tensor

var2 = tf.Variable ([1,2,3,4]) # rank 1 tensor

var3 = tf.Variable([[1,2],[3,4]]) # rank 2 tensor

var3 = tf.Variable([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # rank 3 tensor


In [15]:
var0, var1, var2, var3


(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=24>,
 <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>)

**Reassign a Variable - var.assign()**

In [16]:
var_reassign = tf.Variable(32.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=32.0>

In [17]:
var_reassign.assign(64)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=64.0>

**Add Assign or Sub Assign**



We can assign "=" with assign(value) or

assign.add(value) with "+="


assign.sub(value) with "-="

In [18]:
initial_value = tf.random.normal(shape = (2,2))
a = tf.Variable(initial_value)

In [19]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.5284814 , -2.296176  ],
       [-0.04378971, -1.0175554 ]], dtype=float32)>

In [20]:
new_value = tf.random.normal(shape = (2,2))
a.assign(new_value)

for i in range(2):
  for j in range(2):
    assert a[i, j] == new_value[i,j]

In [21]:
added_value = tf.random.normal(shape = (2,2))
a.assign_add(added_value)
for i in range(2):
  for j in range(2):
    assert a[i, j] == new_value[i,j] + added_value[i,j]

**Shaping a Tensor**

In [22]:
tensor = tf.Variable([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
tensor.shape

TensorShape([2, 2, 3])

In [23]:
tensor1 = tf.reshape(tensor, [2,6]) # 2 rows 6 columns
tensor1.shape

TensorShape([2, 6])

In [24]:
tensor2 = tf.reshape(tensor, [12]) # 1 rows 12 columns
tensor2.shape

TensorShape([12])

**Ranking of Tensor**

The rank of a tensor is the number  of dimensions it has, that is, the number of indices that are required to specify any particular element of that tensor.

In [25]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [26]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

**Specifying an element of tensor**

In [27]:
tensor3 = tensor[1,0,2]
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=9>

**Casting a tensor to Numpy/Python Variable**

In [28]:
print(tensor.numpy())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [29]:
tensor[1,0,2].numpy()

9

**Finding Size (number of elements) of a tensor**

In [30]:
tf.size(tensor)


<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [31]:
tf.size(tensor).numpy()


12

In [32]:
tensor_size = tf.size(tensor).numpy()
tensor_size

12

**DataType of Tensor**

In [33]:
tensor3.dtype

tf.int32

---
---
## **TensorFlow MATHEMATICAL OPERATION**

In [34]:
a = tf.random.normal(shape = (2,2))
b = tf.random.normal(shape = (2,2))
c = a+b
d = tf.square(c)
e = tf.exp(d)

In [35]:
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[ 0.8842885 -2.2341297]
 [ 1.4015937 -2.8528106]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.45809248 -0.48515782]
 [-1.6361428   0.23172992]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.342381   -2.7192874 ]
 [-0.23454916 -2.6210806 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.8019867  7.394524  ]
 [0.05501331 6.870064  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[6.0616784e+00 1.6270504e+03]
 [1.0565547e+00 9.6301001e+02]], shape=(2, 2), dtype=float32)


**Elementwise Premitive Tensorflow Operation**

In [36]:
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[ 49,  64,  81],
        [100, 121, 144]]], dtype=int32)>

In [37]:
tensor-tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int32)>

In [38]:
tensor+tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[14, 16, 18],
        [20, 22, 24]]], dtype=int32)>

**Broadcasting**

In [39]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [40]:
tensor*4

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 4,  8, 12],
        [16, 20, 24]],

       [[28, 32, 36],
        [40, 44, 48]]], dtype=int32)>

**Transpose Matrix Multiplication**

In [41]:
matrix_u = tf.constant([[1,2,3]])
matrix_v = tf.constant([[4,5,6]])

In [42]:
matrix_u

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [43]:
matrix_v

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[4, 5, 6]], dtype=int32)>

In [44]:
tf.matmul(matrix_u,tf.transpose(matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[32]], dtype=int32)>

**Casting a tensor to another(tensor) datatype**

In [45]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [46]:
tensor1 = tf.cast(tensor, dtype = tf.float32)

In [47]:
tensor1

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]], dtype=float32)>

**With Truncation**

In [48]:
i = tf.cast(tf.constant(4.9), dtype = tf.int32)

In [49]:
i

<tf.Tensor: shape=(), dtype=int32, numpy=4>

---
---
## **RAGGED TENSOR**

the tensor with one or more ragged dimensions. Ragged dimensions are the dimensions that have slices  with different length.

Simplest method to declare ragges array is by constant ragged array.

In [50]:
ragged = tf.ragged.constant([[1,2,3,4],[],[2,3],[4,5,6],[1]])

In [51]:
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[1, 2, 3, 4], [], [2, 3], [4, 5, 6], [1]]>
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([1], shape=(1,), dtype=int32)


**Squared Difference between Tensors**

In [52]:
varx = [1,3,5,7]
vary = 4

varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([9, 1, 1, 9], dtype=int32)>

---
---
## **Mean**

In [53]:
numbers = tf.constant([[4.,5.],[6.,7.]])

**Find Mean accross all axes**

In [54]:
tf.reduce_mean(input_tensor = numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=5.5>

**Find Mean accross all columns**

In [55]:
tf.reduce_mean(input_tensor = numbers, axis =0 )

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 6.], dtype=float32)>

**Find Mean accross all rows**

In [56]:
tf.reduce_mean(input_tensor = numbers, axis =1 )

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 6.5], dtype=float32)>

In [57]:
tf.reduce_mean(input_tensor = numbers, axis =1 , keepdims = True)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[4.5],
       [6.5]], dtype=float32)>

---
---
## **Generating Tensor with Random Values**

**using tf.random.normal()**

In [58]:
ran = tf.random.normal(shape = (3,2), mean = 10.0, stddev = 2.0)
ran

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[12.2518215,  9.822757 ],
       [ 9.957996 , 10.515807 ],
       [10.5723505,  7.956753 ]], dtype=float32)>

**using tf.random.uniform()**

In [59]:
ran = tf.random.uniform(shape = (3,2), minval = 0, maxval = 2.0)
ran

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.2779677 , 1.9261463 ],
       [0.01759839, 1.8128707 ],
       [0.5538573 , 1.9288297 ]], dtype=float32)>

---
---
## **Setting the Seed**

In [60]:
tf.random.set_seed(11)

ran1 = tf.random.normal(shape = (3,2), mean = 10.0, stddev = 2.0)

ran2 = tf.random.uniform(shape = (3,2), minval = 0, maxval = 2.0)


In [61]:
ran1, ran2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 6.9541054, 11.339089 ],
        [ 8.71506  , 12.8600855],
        [11.173565 , 10.878596 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1.1165078 , 0.10814166],
        [0.18793845, 1.3831234 ],
        [0.05599403, 0.4248917 ]], dtype=float32)>)

---
---
## **Practical Example of Random Values using Dices**

In [63]:
dice1 = tf.Variable(tf.random.uniform([10,1], minval = 1, maxval=7, dtype = tf.int32))
dice2 = tf.Variable(tf.random.uniform([10,1],minval = 1, maxval=7, dtype = tf.int32))

dice_sum = dice1 + dice2

In [64]:
# Concatinate all these matrix

result_matrix = tf.concat(values = [dice1, dice2, dice_sum], axis = 1)
result_matrix

<tf.Tensor: shape=(10, 3), dtype=int32, numpy=
array([[ 5,  5, 10],
       [ 3,  2,  5],
       [ 3,  4,  7],
       [ 3,  1,  4],
       [ 4,  3,  7],
       [ 1,  5,  6],
       [ 1,  6,  7],
       [ 4,  1,  5],
       [ 3,  2,  5],
       [ 3,  3,  6]], dtype=int32)>

---
---
## **Max and Min value**

In [65]:
t = tf.constant([1,2,3,4,5])

In [69]:
i = tf.argmax(input = t)
print(" location is : {}".format(i))
print(" Value is : {}".format(t[i]))

 location is : 4
 Value is : 5


In [70]:
i = tf.argmin(input = t)
print(" location is : {}".format(i))
print(" Value is : {}".format(t[i]))

 location is : 0
 Value is : 1


---
---
## **Saving and Restoring Tensor Values using CheckPoint**

In [71]:
variable = tf.Variable(([1,2,3,4],[5,6,7,8]))

checkpoint = tf.train.Checkpoint(var = variable)

save_path = checkpoint.save("./vars")

variable.assign(([0,0,0,0],[0,0,0,0]))

variable

checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>


---
---
## **Finding the indices of largest and smallest element**

In [72]:
t = tf.Variable(([1,2,3,4],[5,6,7,8]))
t

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [76]:
max = tf.argmax(input = t, axis = 1)
print(" Maximum Value Location : {}".format(max))

 Maximum Value Location : [3 3]
 Maximum Values are     : [3 3]


In [80]:
max = tf.argmax(input = t, axis = 0)
print(" Maximum Value Location : {}".format(max))

 Maximum Value Location : [1 1 1 1]


In [78]:
min = tf.argmin(input = t, axis = 1)
print(" Minimum Value Location : {}".format(min))

 Minimum Value Location : [0 0]


In [79]:
min = tf.argmin(input = t, axis = 0)
print(" Minimum Value Location : {}".format(min))

 Minimum Value Location : [0 0 0 0]


---
---
## **Calculate the Gradiant**

In [81]:
a = tf.random.normal(shape = (2,2))
b = tf.random.normal(shape = (2,2))

In [83]:
a, b

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 1.6126053 , -0.12196143],
        [ 0.9344708 , -0.43732217]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.28425562, -0.49051556],
        [ 0.7645078 ,  0.41764784]], dtype=float32)>)

In [84]:
with tf.GradientTape() as tape:
  tape.watch(a)
  c = tf.sqrt(tf.square(a)+tf.square(b))
  dc_da = tape.gradient(c,a)
  print(dc_da)

tf.Tensor(
[[ 0.98481715 -0.24129257]
 [ 0.77398133 -0.7231871 ]], shape=(2, 2), dtype=float32)
