# **Pytorch**
---
---

In [1]:
import torch

In [2]:
torch.__version__

'2.0.1+cu118'

---
---
## **Convert Numpy to Pytorch Tensors**

In [3]:
# Creating Numpy array

import numpy as np

list = [1, 2, 3, 4]
arr = np.array(list)

arr

array([1, 2, 3, 4])

In [4]:
arr.dtype

dtype('int64')

In [5]:
# converting Numpy arr to pytorch tensor

tensor = torch.from_numpy(arr)
tensor

tensor([1, 2, 3, 4])

In [6]:
tensor.dtype

torch.int64

In [7]:
# Indexing - same as numpy

tensor[:2]

tensor([1, 2])

In [8]:
tensor[2]

tensor(3)

In [9]:
tensor[1:4]

tensor([2, 3, 4])

**Disadvantage from Numpy : both uses the same memory Loacation**

In [10]:
tensor

tensor([1, 2, 3, 4])

In [11]:
tensor[2] = 100
tensor

tensor([  1,   2, 100,   4])

In [12]:
arr

array([  1,   2, 100,   4])

# **torch.tensor - Prevent the above problem**

In [13]:
list = [1, 2, 3, 4]
arr = np.array(list)

In [14]:
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([1, 2, 3, 4])

In [15]:
tensor_arr[2] = 100
tensor_arr

tensor([  1,   2, 100,   4])

In [16]:
arr

array([1, 2, 3, 4])

---
---
## **Zeros and Ones Matrix**

In [17]:
torch.zeros(2,3, dtype = torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [18]:
torch.ones(2,3, dtype = torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

---
---
## **Mathematical Operation**

In [19]:
a = torch.tensor([1, 2, 3, 4], dtype = torch.float)
b = torch.tensor([5, 6, 7, 8], dtype = torch.float)

In [20]:
# Sum

torch.add(a,b)

tensor([ 6.,  8., 10., 12.])

In [21]:
# Store the output


c = torch.zeros(1,4)
c

tensor([[0., 0., 0., 0.]])

In [22]:
torch.add(a,b, out = c)

<ipython-input-22-93012b6d1f6a>:1: UserWarning: An output with one or more elements was resized since it had shape [1, 4], which does not match the required output shape [4]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:26.)
  torch.add(a,b, out = c)


tensor([ 6.,  8., 10., 12.])

In [23]:
c

tensor([ 6.,  8., 10., 12.])

In [24]:
# Sum of all elements - sum()

torch.add(a,b).sum()

tensor(36.)

In [25]:
c.sum()

tensor(36.)

---
---
## **Dot Products and Multiplication Operation**

In [26]:
a = torch.tensor([1, 2, 3, 4], dtype = torch.float)
b = torch.tensor([5, 6, 7, 8], dtype = torch.float)

In [27]:
# Multiplication Operation

a.mul(b)

tensor([ 5., 12., 21., 32.])

In [28]:
# Dot Product

a.dot(b)

tensor(70.)

---
---
## **Matrix Multiplication**

In [29]:
a = torch.tensor([[1, 2, 3, 4],[1, 2, 3, 4]])
b = torch.tensor([[5, 6],[7, 8],[9,10],[11,12]])

In [30]:
# method 1

torch.matmul(a,b)

tensor([[ 90, 100],
        [ 90, 100]])

In [31]:
# method 2

torch.mm(a,b)

tensor([[ 90, 100],
        [ 90, 100]])

In [32]:
# method 3

a@b

tensor([[ 90, 100],
        [ 90, 100]])